import type { Product, ProductImage } from "@/types";
import { categories } from "./categories";

function toneFor(categorySlug: string) {
  const category = categories.find((c) => c.slug === categorySlug);
  return { tone: category?.tone ?? "#ECEAE6", toneDark: category?.toneDark ?? "#262420" };
}

function images(id: string, icon: string, categorySlug: string, count = 4): ProductImage[] {
  const { tone, toneDark } = toneFor(categorySlug);
  return Array.from({ length: count }, (_, i) => ({
    id: `${id}-img-${i}`,
    tone,
    toneDark,
    icon,
    alt: `${id} product view ${i + 1}`,
  }));
}

const neutralColors = [
  { name: "Graphite", hex: "#1F1F1F" },
  { name: "Sand", hex: "#D8CDB8" },
  { name: "Birch", hex: "#EDEAE2" },
];

const apparelColors = [
  { name: "Ink", hex: "#15181C" },
  { name: "Clay", hex: "#B9806B" },
  { name: "Stone", hex: "#9C9A91" },
  { name: "Olive", hex: "#5C5F4D" },
];

const apparelSizes = ["XS", "S", "M", "L", "XL"];

export const products: Product[] = [
  {
    id: "p-aria-headphones",
    slug: "aria-wireless-headphones",
    name: "Aria Wireless Headphones",
    brand: "Halo Audio",
    category: "audio",
    collection: "Studio Series",
    price: 349,
    compareAtPrice: 399,
    currency: "USD",
    shortDescription: "Hand-assembled over-ear headphones with 40-hour battery life.",
    description:
      "Aria pairs a custom 40mm driver with memory-foam ear cups for studio-grade clarity you can wear all day. Aluminum yoke construction keeps weight under 280g, and active noise cancellation adapts in real time to your environment. Forty hours of playback on a single charge, with 10-minute fast charging for three hours of listening.",
    rating: 4.8,
    reviewCount: 412,
    colors: neutralColors,
    sizes: [],
    tags: ["wireless", "anc", "over-ear"],
    images: images("p-aria-headphones", "Headphones", "audio"),
    features: [
      { title: "Adaptive ANC", description: "Recalibrates 200 times per second to ambient noise.", icon: "Waves" },
      { title: "40-hour battery", description: "A full week of commutes on one charge.", icon: "BatteryFull" },
      { title: "Aluminum yoke", description: "Aerospace-grade alloy, under 280g.", icon: "Feather" },
    ],
    stock: 86,
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    createdAt: "2025-09-02",
  },
  {
    id: "p-pebble-speaker",
    slug: "pebble-mini-speaker",
    name: "Pebble Mini Speaker",
    brand: "Aro Studio",
    category: "audio",
    price: 129,
    currency: "USD",
    shortDescription: "Pocket-sized speaker with room-filling, balanced sound.",
    description:
      "Pebble fits in your palm but plays loud and clean thanks to a dual-passive radiator design tuned in our Stockholm studio. IP67-rated for poolside and trailhead use, with 12 hours of battery and USB-C charging.",
    rating: 4.6,
    reviewCount: 203,
    colors: neutralColors,
    sizes: [],
    tags: ["portable", "waterproof"],
    images: images("p-pebble-speaker", "Speaker", "audio"),
    features: [
      { title: "IP67 rated", description: "Dust-tight and submersible to 1 meter.", icon: "Droplets" },
      { title: "12-hour battery", description: "All-day playback, USB-C fast charge.", icon: "BatteryFull" },
      { title: "Dual radiators", description: "Bass response well beyond its size.", icon: "Waves" },
    ],
    stock: 142,
    isNew: true,
    isFeatured: true,
    isBestSeller: false,
    createdAt: "2026-04-18",
  },
  {
    id: "p-loop-earbuds",
    slug: "loop-earbuds",
    name: "Loop Earbuds",
    brand: "Halo Audio",
    category: "audio",
    price: 199,
    compareAtPrice: 229,
    currency: "USD",
    shortDescription: "True wireless earbuds with a featherlight, all-day fit.",
    description:
      "Loop's ergonomic shell was modeled from over 1,200 ear scans for a fit that disappears. Each bud weighs 4.2 grams, with six hours of playback and a pocketable case good for three additional charges.",
    rating: 4.5,
    reviewCount: 318,
    colors: neutralColors,
    sizes: [],
    tags: ["wireless", "earbuds"],
    images: images("p-loop-earbuds", "Headphones", "audio"),
    features: [
      { title: "Ergonomic shell", description: "Modeled from 1,200+ ear scans.", icon: "Ear" },
      { title: "4.2g per bud", description: "Forget you're wearing them.", icon: "Feather" },
      { title: "24hr with case", description: "Three additional charges on the go.", icon: "BatteryFull" },
    ],
    stock: 97,
    isNew: false,
    isFeatured: false,
    isBestSeller: true,
    createdAt: "2025-11-22",
  },
  {
    id: "p-field-speaker",
    slug: "field-recorder-speaker",
    name: "Field Recorder Speaker",
    brand: "Norr",
    category: "audio",
    price: 249,
    currency: "USD",
    shortDescription: "Retro-inspired speaker with analog warmth and modern range.",
    description:
      "Inspired by tape field recorders, this speaker pairs a warm analog-tuned amplifier with modern Bluetooth 5.3 range. Wrapped in water-resistant canvas with a leather carry strap.",
    rating: 4.4,
    reviewCount: 88,
    colors: neutralColors,
    sizes: [],
    tags: ["retro", "portable"],
    images: images("p-field-speaker", "Speaker", "audio"),
    features: [
      { title: "Analog-tuned amp", description: "Warmth without losing detail.", icon: "Waves" },
      { title: "Canvas + leather", description: "Water-resistant shell, leather strap.", icon: "Briefcase" },
      { title: "Bluetooth 5.3", description: "Stable range up to 15 meters.", icon: "Bluetooth" },
    ],
    stock: 54,
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2025-07-14",
  },
  {
    id: "p-weekender-duffel",
    slug: "weekender-duffel",
    name: "Weekender Duffel",
    brand: "Fielder Co.",
    category: "carry",
    collection: "Voyage",
    price: 295,
    currency: "USD",
    shortDescription: "Full-grain leather duffel sized for a long weekend.",
    description:
      "Built on a single piece of full-grain leather that softens beautifully with use. A removable shoulder strap and brass hardware make it as comfortable for a flight as it is for the gym.",
    rating: 4.9,
    reviewCount: 156,
    colors: neutralColors,
    sizes: [],
    tags: ["leather", "travel"],
    images: images("p-weekender-duffel", "Luggage", "carry"),
    features: [
      { title: "Full-grain leather", description: "Ages and softens with every trip.", icon: "Briefcase" },
      { title: "45L capacity", description: "Fits airline carry-on sizing.", icon: "Package" },
      { title: "Brass hardware", description: "Solid brass zips and rivets.", icon: "Gem" },
    ],
    stock: 41,
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    createdAt: "2025-08-30",
  },
  {
    id: "p-daily-tote",
    slug: "daily-tote",
    name: "Daily Tote",
    brand: "Aro Studio",
    category: "carry",
    price: 165,
    compareAtPrice: 195,
    currency: "USD",
    shortDescription: "Structured canvas tote with a padded laptop sleeve.",
    description:
      "A no-fuss tote in waxed canvas, structured enough to hold its shape empty and roomy enough for a laptop, notebook, and a change of shoes.",
    rating: 4.7,
    reviewCount: 211,
    colors: neutralColors,
    sizes: [],
    tags: ["canvas", "everyday"],
    images: images("p-daily-tote", "Backpack", "carry"),
    features: [
      { title: "Waxed canvas", description: "Naturally water-resistant finish.", icon: "Droplets" },
      { title: "Padded sleeve", description: "Fits up to a 16-inch laptop.", icon: "Package" },
      { title: "Self-standing base", description: "Structured to hold its shape.", icon: "Box" },
    ],
    stock: 132,
    isNew: false,
    isFeatured: true,
    isBestSeller: false,
    createdAt: "2025-10-05",
  },
  {
    id: "p-commuter-backpack",
    slug: "commuter-backpack",
    name: "Commuter Backpack",
    brand: "Fielder Co.",
    category: "carry",
    price: 245,
    currency: "USD",
    shortDescription: "Weatherproof backpack with a dedicated laptop compartment.",
    description:
      "A single-compartment backpack designed around how you actually move through a day — quick-access pocket for your phone and cards, a fleece-lined sleeve for your laptop, and a hidden back panel pocket for travel documents.",
    rating: 4.6,
    reviewCount: 174,
    colors: neutralColors,
    sizes: [],
    tags: ["weatherproof", "commuter"],
    images: images("p-commuter-backpack", "Backpack", "carry"),
    features: [
      { title: "Weatherproof shell", description: "Sealed seams, water-repellent zips.", icon: "Droplets" },
      { title: "Fleece-lined sleeve", description: "Protects up to a 16-inch laptop.", icon: "Package" },
      { title: "Hidden back pocket", description: "Quick access to travel documents.", icon: "Lock" },
    ],
    stock: 78,
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2026-03-11",
  },
  {
    id: "p-passport-pouch",
    slug: "passport-pouch",
    name: "Passport Pouch",
    brand: "Maren",
    category: "carry",
    price: 85,
    currency: "USD",
    shortDescription: "Compact leather organizer for documents and cards.",
    description:
      "A slim leather pouch that holds passports for the whole family, boarding passes, and a slim stack of cards — small enough to disappear into a tote.",
    rating: 4.5,
    reviewCount: 64,
    colors: neutralColors,
    sizes: [],
    tags: ["leather", "travel"],
    images: images("p-passport-pouch", "Luggage", "carry"),
    features: [
      { title: "Holds 4 passports", description: "Plus boarding passes and cards.", icon: "Package" },
      { title: "Vegetable-tanned leather", description: "Develops a rich patina over time.", icon: "Gem" },
    ],
    stock: 165,
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2025-06-19",
  },
  {
    id: "p-index-watch",
    slug: "index-watch",
    name: "Index Watch",
    brand: "Sten & Co",
    category: "wearables",
    collection: "Index",
    price: 420,
    currency: "USD",
    shortDescription: "Automatic watch with a sapphire crystal and steel case.",
    description:
      "A 38mm stainless steel case houses a Swiss automatic movement visible through an exhibition case back. Sapphire crystal front and back resist scratches for a lifetime of wear.",
    rating: 4.9,
    reviewCount: 132,
    colors: [
      { name: "Steel", hex: "#9CA3AF" },
      { name: "Black", hex: "#171717" },
    ],
    sizes: [],
    tags: ["automatic", "steel"],
    images: images("p-index-watch", "Watch", "wearables"),
    features: [
      { title: "Swiss automatic", description: "42-hour power reserve.", icon: "Clock" },
      { title: "Sapphire crystal", description: "Front and case back, scratch resistant.", icon: "Gem" },
      { title: "100m water resistant", description: "Rated for swimming and diving.", icon: "Droplets" },
    ],
    stock: 28,
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    createdAt: "2025-05-12",
  },
  {
    id: "p-aro-ring",
    slug: "aro-ring",
    name: "Aro Ring",
    brand: "Aro Studio",
    category: "wearables",
    price: 145,
    currency: "USD",
    shortDescription: "Minimal sterling silver band, hand-finished.",
    description:
      "A single, continuous band cast in recycled sterling silver and hand-polished to a soft satin finish. Designed to be worn alone or stacked.",
    rating: 4.7,
    reviewCount: 89,
    colors: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Gold", hex: "#C9A227" },
    ],
    sizes: ["6", "7", "8", "9", "10"],
    tags: ["jewelry", "recycled"],
    images: images("p-aro-ring", "Gem", "wearables"),
    features: [
      { title: "Recycled sterling silver", description: "Responsibly sourced material.", icon: "Recycle" },
      { title: "Hand-finished", description: "Satin polish, one piece at a time.", icon: "Sparkles" },
    ],
    stock: 210,
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2026-02-27",
  },
  {
    id: "p-trail-watch",
    slug: "trail-watch",
    name: "Trail Watch",
    brand: "Sten & Co",
    category: "wearables",
    price: 380,
    compareAtPrice: 420,
    currency: "USD",
    shortDescription: "Rugged field watch with luminous markers.",
    description:
      "A 40mm titanium case built for the trail — luminous markers for low light, a unidirectional bezel, and a quick-release strap for swapping between canvas and rubber.",
    rating: 4.6,
    reviewCount: 71,
    colors: [
      { name: "Titanium", hex: "#878681" },
      { name: "Olive", hex: "#5C5F4D" },
    ],
    sizes: [],
    tags: ["titanium", "field"],
    images: images("p-trail-watch", "Watch", "wearables"),
    features: [
      { title: "Titanium case", description: "Lightweight and corrosion resistant.", icon: "Shield" },
      { title: "Luminous markers", description: "Legible in low light.", icon: "Sparkles" },
      { title: "Quick-release strap", description: "Swap straps without tools.", icon: "Repeat" },
    ],
    stock: 33,
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2025-09-28",
  },
  {
    id: "p-cuff-bracelet",
    slug: "cuff-bracelet",
    name: "Cuff Bracelet",
    brand: "Maren",
    category: "wearables",
    price: 95,
    currency: "USD",
    shortDescription: "Brushed brass cuff with an adjustable fit.",
    description:
      "An open cuff in brushed brass that adjusts to fit most wrists. Designed to pair with the Index Watch or worn solo.",
    rating: 4.4,
    reviewCount: 38,
    colors: [
      { name: "Brass", hex: "#B08D57" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    sizes: [],
    tags: ["jewelry"],
    images: images("p-cuff-bracelet", "Gem", "wearables"),
    features: [
      { title: "Adjustable fit", description: "One size fits most wrists.", icon: "Sparkles" },
    ],
    stock: 120,
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2025-04-02",
  },
  {
    id: "p-merino-crew",
    slug: "merino-crew",
    name: "Merino Crew",
    brand: "Loma",
    category: "apparel",
    price: 120,
    currency: "USD",
    shortDescription: "17-micron merino crewneck that regulates temperature.",
    description:
      "Knit from 17-micron merino wool sourced from New Zealand, this crewneck breathes in warm weather and insulates in cold — soft enough for next-to-skin wear, durable enough for daily rotation.",
    rating: 4.8,
    reviewCount: 264,
    colors: apparelColors,
    sizes: apparelSizes,
    tags: ["merino", "essentials"],
    images: images("p-merino-crew", "Shirt", "apparel"),
    features: [
      { title: "17-micron merino", description: "Soft enough for next-to-skin wear.", icon: "Feather" },
      { title: "Temperature regulating", description: "Breathable in heat, warm in cold.", icon: "Thermometer" },
      { title: "Odor resistant", description: "Naturally antimicrobial fibers.", icon: "Wind" },
    ],
    stock: 188,
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    createdAt: "2025-08-11",
  },
  {
    id: "p-field-jacket",
    slug: "field-jacket",
    name: "Field Jacket",
    brand: "Fielder Co.",
    category: "apparel",
    price: 295,
    currency: "USD",
    shortDescription: "Waxed cotton jacket with a wool-blend lining.",
    description:
      "A four-pocket field jacket in waxed organic cotton, lined with a brushed wool blend for warmth without bulk. Built to be re-waxed and worn for decades.",
    rating: 4.7,
    reviewCount: 142,
    colors: apparelColors,
    sizes: apparelSizes,
    tags: ["waxed-cotton", "outerwear"],
    images: images("p-field-jacket", "Shirt", "apparel"),
    features: [
      { title: "Waxed organic cotton", description: "Re-waxable for decades of wear.", icon: "Droplets" },
      { title: "Wool-blend lining", description: "Warmth without added bulk.", icon: "Thermometer" },
    ],
    stock: 64,
    isNew: false,
    isFeatured: true,
    isBestSeller: false,
    createdAt: "2025-10-21",
  },
  {
    id: "p-relaxed-trouser",
    slug: "relaxed-trouser",
    name: "Relaxed Trouser",
    brand: "Loma",
    category: "apparel",
    price: 165,
    compareAtPrice: 190,
    currency: "USD",
    shortDescription: "Tapered trouser in brushed Japanese twill.",
    description:
      "A relaxed-through-the-thigh, tapered-at-the-ankle trouser cut from brushed Japanese cotton twill. An elasticated waistband sits cleanly under a shirt or jacket.",
    rating: 4.5,
    reviewCount: 97,
    colors: apparelColors,
    sizes: apparelSizes,
    tags: ["twill", "essentials"],
    images: images("p-relaxed-trouser", "Shirt", "apparel"),
    features: [
      { title: "Japanese twill", description: "Brushed for softness, holds shape.", icon: "Feather" },
      { title: "Elasticated waist", description: "Clean lines, all-day comfort.", icon: "Sparkles" },
    ],
    stock: 110,
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2026-01-30",
  },
  {
    id: "p-recycled-shell",
    slug: "recycled-shell",
    name: "Recycled Shell",
    brand: "Norr",
    category: "apparel",
    price: 225,
    currency: "USD",
    shortDescription: "Packable rain shell made from recycled fishing nets.",
    description:
      "A fully seam-sealed rain shell woven from regenerated nylon recovered from fishing nets. Packs into its own chest pocket for travel.",
    rating: 4.6,
    reviewCount: 58,
    colors: apparelColors,
    sizes: apparelSizes,
    tags: ["recycled", "rain-shell"],
    images: images("p-recycled-shell", "Shirt", "apparel"),
    features: [
      { title: "Regenerated nylon", description: "Made from recovered fishing nets.", icon: "Recycle" },
      { title: "Seam-sealed", description: "Fully waterproof construction.", icon: "Droplets" },
      { title: "Packable", description: "Folds into its own chest pocket.", icon: "Package" },
    ],
    stock: 49,
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2026-05-09",
  },
  {
    id: "p-arc-lamp",
    slug: "arc-table-lamp",
    name: "Arc Table Lamp",
    brand: "Aro Studio",
    category: "home",
    price: 185,
    currency: "USD",
    shortDescription: "Dimmable table lamp in spun aluminum.",
    description:
      "A spun-aluminum shade throws warm, directional light across a desk or console. Touch-dimmable with three color temperature settings.",
    rating: 4.8,
    reviewCount: 121,
    colors: neutralColors,
    sizes: [],
    tags: ["lighting", "dimmable"],
    images: images("p-arc-lamp", "Lamp", "home"),
    features: [
      { title: "Touch dimming", description: "Three color temperatures.", icon: "Sun" },
      { title: "Spun aluminum", description: "Cast and finished by hand.", icon: "Box" },
    ],
    stock: 73,
    isNew: false,
    isFeatured: true,
    isBestSeller: false,
    createdAt: "2025-07-03",
  },
  {
    id: "p-candle-trio",
    slug: "stone-candle-trio",
    name: "Stone Candle Trio",
    brand: "Maren",
    category: "home",
    price: 65,
    currency: "USD",
    shortDescription: "Three soy candles in hand-cast stone vessels.",
    description:
      "Three signature scents — Fig Leaf, Cedar, and Sea Salt — poured into vessels cast from natural stone composite. Each burns for approximately 45 hours.",
    rating: 4.6,
    reviewCount: 76,
    colors: neutralColors,
    sizes: [],
    tags: ["candle", "gift"],
    images: images("p-candle-trio", "Sparkles", "home"),
    features: [
      { title: "45-hour burn", description: "Per candle, soy wax blend.", icon: "Flame" },
      { title: "Stone vessels", description: "Reusable after the candle is spent.", icon: "Box" },
    ],
    stock: 96,
    isNew: false,
    isFeatured: false,
    isBestSeller: true,
    createdAt: "2025-11-08",
  },
  {
    id: "p-linen-throw",
    slug: "linen-throw",
    name: "Linen Throw",
    brand: "Loma",
    category: "home",
    price: 95,
    currency: "USD",
    shortDescription: "Stonewashed linen throw, woven in Portugal.",
    description:
      "A generously sized throw in 100% stonewashed linen, woven in Portugal for a soft hand-feel that improves with every wash.",
    rating: 4.7,
    reviewCount: 54,
    colors: apparelColors,
    sizes: [],
    tags: ["linen", "home"],
    images: images("p-linen-throw", "Shirt", "home"),
    features: [
      { title: "100% linen", description: "Stonewashed for softness.", icon: "Feather" },
      { title: "Woven in Portugal", description: "Small-batch production.", icon: "Box" },
    ],
    stock: 88,
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2025-06-25",
  },
  {
    id: "p-pour-over",
    slug: "ceramic-pour-over-set",
    name: "Ceramic Pour-Over Set",
    brand: "Aro Studio",
    category: "home",
    price: 115,
    compareAtPrice: 135,
    currency: "USD",
    shortDescription: "Hand-thrown ceramic dripper, server, and filters.",
    description:
      "A hand-thrown stoneware dripper paired with a matching server, designed with a slow-flow ridge pattern for even extraction. Includes 50 reusable cotton filters.",
    rating: 4.9,
    reviewCount: 143,
    colors: neutralColors,
    sizes: [],
    tags: ["ceramic", "coffee"],
    images: images("p-pour-over", "Box", "home"),
    features: [
      { title: "Hand-thrown stoneware", description: "Slow-flow ridge for even extraction.", icon: "Box" },
      { title: "Includes filters", description: "50 reusable cotton filters included.", icon: "Package" },
    ],
    stock: 67,
    isNew: true,
    isFeatured: true,
    isBestSeller: false,
    createdAt: "2026-04-02",
  },
  {
    id: "p-halden-sunglasses",
    slug: "halden-sunglasses",
    name: "Halden Sunglasses",
    brand: "Maren",
    category: "eyewear",
    price: 210,
    currency: "USD",
    shortDescription: "Acetate sunglasses with polarized lenses.",
    description:
      "Hand-cut from Italian acetate and fitted with polarized, scratch-resistant lenses. A keyhole bridge and wide temple keep them comfortable for all-day wear.",
    rating: 4.7,
    reviewCount: 167,
    colors: [
      { name: "Tortoise", hex: "#6B4A2F" },
      { name: "Black", hex: "#171717" },
      { name: "Sand", hex: "#D8CDB8" },
    ],
    sizes: [],
    tags: ["acetate", "polarized"],
    images: images("p-halden-sunglasses", "Glasses", "eyewear"),
    features: [
      { title: "Polarized lenses", description: "Cuts glare without distorting color.", icon: "Sun" },
      { title: "Italian acetate", description: "Hand-cut and polished.", icon: "Sparkles" },
    ],
    stock: 92,
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    createdAt: "2025-05-30",
  },
  {
    id: "p-reading-frame",
    slug: "reading-frame",
    name: "Reading Frame",
    brand: "Maren",
    category: "eyewear",
    price: 175,
    currency: "USD",
    shortDescription: "Lightweight acetate reading glasses.",
    description:
      "A lightweight frame designed specifically for reading, with anti-reflective coated lenses available in four strengths.",
    rating: 4.5,
    reviewCount: 49,
    colors: [
      { name: "Tortoise", hex: "#6B4A2F" },
      { name: "Black", hex: "#171717" },
    ],
    sizes: [],
    tags: ["acetate", "reading"],
    images: images("p-reading-frame", "Glasses", "eyewear"),
    features: [
      { title: "Anti-reflective coating", description: "Reduces glare from screens.", icon: "Sun" },
      { title: "Four strengths", description: "+1.00 through +2.50.", icon: "Sparkles" },
    ],
    stock: 134,
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2025-09-15",
  },
  {
    id: "p-sport-shades",
    slug: "cycle-sport-shades",
    name: "Cycle Sport Shades",
    brand: "Norr",
    category: "eyewear",
    price: 190,
    compareAtPrice: 220,
    currency: "USD",
    shortDescription: "Performance shield lens with interchangeable tints.",
    description:
      "A wraparound shield lens built for speed, with a hydrophobic coating and two interchangeable tints for changing light. Grip nose and temple pads stay put through sweat.",
    rating: 4.4,
    reviewCount: 61,
    colors: [
      { name: "Black", hex: "#171717" },
      { name: "Olive", hex: "#5C5F4D" },
    ],
    sizes: [],
    tags: ["performance", "interchangeable"],
    images: images("p-sport-shades", "Glasses", "eyewear"),
    features: [
      { title: "Interchangeable tints", description: "Two lenses included.", icon: "Repeat" },
      { title: "Hydrophobic coating", description: "Sheds sweat and rain.", icon: "Droplets" },
    ],
    stock: 58,
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2026-03-22",
  },
  {
    id: "p-acetate-round",
    slug: "acetate-round",
    name: "Acetate Round",
    brand: "Maren",
    category: "eyewear",
    price: 195,
    currency: "USD",
    shortDescription: "Round acetate frame with UV400 lenses.",
    description:
      "A classic round silhouette in thick Italian acetate, fitted with UV400-rated lenses and finished with hand-polished edges.",
    rating: 4.6,
    reviewCount: 73,
    colors: [
      { name: "Tortoise", hex: "#6B4A2F" },
      { name: "Sand", hex: "#D8CDB8" },
    ],
    sizes: [],
    tags: ["acetate", "round"],
    images: images("p-acetate-round", "Glasses", "eyewear"),
    features: [
      { title: "UV400 protection", description: "Full UV-blocking lenses.", icon: "Sun" },
      { title: "Hand-polished", description: "Finished edge by edge.", icon: "Sparkles" },
    ],
    stock: 84,
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    createdAt: "2025-12-19",
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export const brands = Array.from(new Set(products.map((p) => p.brand))).sort();
export const allColors = Array.from(
  new Map(products.flatMap((p) => p.colors).map((c) => [c.name, c])).values()
);
export const allSizes = Array.from(new Set(products.flatMap((p) => p.sizes)));
export const priceBounds = {
  min: Math.floor(Math.min(...products.map((p) => p.price)) / 10) * 10,
  max: Math.ceil(Math.max(...products.map((p) => p.price)) / 10) * 10,
};
